development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shop_scaffold_d
  pool: 5
  username: root
  password: "1111"
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shop_scaffold_d
  pool: 5
  username: root
  password: "1111"
  host: localhost